name       : ed
version    : '1.18'
release    : 8
source     :
    - https://ftp.gnu.org/gnu/ed/ed-1.18.tar.lz : aca8efad9800c587724a20b97aa8fc47e6b5a47df81606feaba831b074462b4f
homepage   : https://www.gnu.org/software/ed/
license    : GPL-3.0-or-later
component  : editor
summary    : A POSIX-compliant line-oriented text editor
description: |
    GNU ed is a line-oriented text editor. It is used to create, display, modify and otherwise manipulate text files, both interactively and via shell scripts. A restricted version of ed, red, can only edit files in the current directory and cannot execute shell commands. Ed is the "standard" text editor in the sense that it is the original editor for Unix, and thus widely available.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %make_install install-man
