name       : ed
version    : 1.14.1
release    : 2
source     :
    - http://gnu.uberglobalmirror.com/ed/ed-1.14.1.tar.lz : ffb97eb8f2a2b5a71a9b97e3872adce953aa1b8958e04c5b7bf11d556f32552a
license    : GPL-3.0
component  : editor
summary    : A POSIX-compliant line-oriented text editor
description: |
    A POSIX-compliant line-oriented text editor
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %make_install install-man
