name       : ed
version    : 1.14.2
release    : 3
source     :
    - http://gnu.uberglobalmirror.com/ed/ed-1.14.2.tar.lz : f57962ba930d70d02fc71d6be5c5f2346b16992a455ab9c43be7061dec9810db
license    : GPL-3.0
component  : editor
summary    : A POSIX-compliant line-oriented text editor
description: |
    A POSIX-compliant line-oriented text editor
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %make_install install-man
