name       : ed
version    : 1.13
release    : 1
source     :
    - https://ftp.gnu.org/gnu/ed/ed-1.13.tar.lz : cd66c54a53cd6ef35a217556e7b2b2fdd973ca2708f4fc41636b0bc06388c7d3
license    : GPL-2.0 # CHECK ME
summary    : A POSIX-compliant line-oriented text editor
description: |
    A POSIX-compliant line-oriented text editor
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %make_install install-man
