name       : ed
version    : '1.15'
release    : 4
source     :
    - http://gnu.uberglobalmirror.com/ed/ed-1.15.tar.lz : ad4489c0ad7a108c514262da28e6c2a426946fb408a3977ef1ed34308bdfd174
license    : GPL-3.0
component  : editor
summary    : A POSIX-compliant line-oriented text editor
description: |
    A POSIX-compliant line-oriented text editor
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %make_install install-man
