name       : ed
version    : '1.19'
release    : 9
source     :
    - https://ftp.gnu.org/gnu/ed/ed-1.19.tar.lz : ce2f2e5c424790aa96d09dacb93d9bbfdc0b7eb6249c9cb7538452e8ec77cd48
homepage   : https://www.gnu.org/software/ed/
license    : GPL-2.0-or-later
component  : editor
summary    : A POSIX-compliant line-oriented text editor
description: |
    GNU ed is a line-oriented text editor. It is used to create, display, modify and otherwise manipulate text files, both interactively and via shell scripts. A restricted version of ed, red, can only edit files in the current directory and cannot execute shell commands. Ed is the "standard" text editor in the sense that it is the original editor for Unix, and thus widely available.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    %make_install install-man
